# R.Gacesa (2022, UMCG)
# 
# Runner script for strainphlan
#
# DESCRIPTION:
# > script takes input file with clades 
#   (typically generated by running profileClades.sh and profileCladesParse.py)
#   and submits one strainphlan job for each clade in the input file
#
# NOTES:
# > $1 is input file generated by profileCladesParse.py
# > SLURM error / out are sent to JOB_OUT folder

# PARAMS
RUNJOB=/data/umcg-tifn/rgacesa/dag3_pipeline_3c/strainphlan/runMarkerComparison.sh
CPUS=6
MEM=24gb
TIME=0-07:59:00
IN=$1

# HELP / USE
echo "Strainphlan runner script started"
if [[ $# -ne 2 ]];
    then
    echo "ERROR: script requires two command line parameters:"
    echo " <folder with .pkl files to profile>"
    echo " <input file with clades to profile (one clade per line)>"
    exit 2
fi

# make folder for results if it does not exist already
mkdir -p ./JOB_OUT

# Iterate over input file and submit one job per clade (line in a file):
echo "> Processing $2"
while read l
do
   echo "  > submitting job for ${l}"   
   sbatch -o "./JOB_OUT/${l}.out" -e "./JOB_OUT/${l}.err" --mem="$MEM" --cpus-per-task="$CPUS" -t "$TIME" $RUNJOB ${IN} ${l}
   #echo sbatch $RUNJOB ${IN} ${l} -o ./JOB_OUT/${l}.out -e ./JOB_OUT/${l}.err --mem=$MEM --cpus-per-task=$CPUS -t $TIME
done < $2
echo "> DONE, ALL JOBS SUBMITTED!"
